name: Deploy Kaosta

on:
  push:
    branches:
      - main

concurrency:
  group: deploy-hostinger
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          coverage: none
          tools: composer

      - name: Install Composer Dependencies
        run: composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader

      - name: Cache Composer
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ runner.os }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            composer-${{ runner.os }}-

      # === Node & Vite build ===
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install frontend deps (npm)
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build assets (Vite)
        run: npm run build

      # Dry run dulu (storage TIDAK di-exclude)
      - name: FTP Deploy (Dry Run)
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/kaosta.site/kaosta/
          local-dir: ./
          dry-run: true
          exclude: |
            **/.git*
            **/node_modules/**
            node_modules/**
            vendor/**
            vendor/**/*
            .env
            .env.*
            tests/**
            tests/**/*

      # Upload (storage IKUT diupload untuk first commit)
      - name: Upload Files via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /domains/kaosta.site/kaosta/
          local-dir: ./
          exclude: |
            **/.git*
            **/node_modules/**
            node_modules/**
            vendor/**
            vendor/**/*
            .env
            .env.*
            tests/**
            tests/**/*
